kind: pipeline
type: docker
name: ci-pipeline

steps:
  - name: build
    image: jacob9706/golang-opengl:1.13
    environment:
      GO111MODULE: on
      CGO_ENABLED: 1
    commands:
      - go build ./main.go
